# Site settings
title: Taylor Fraser
subtitle: a Web Portfolio
email: taylor.fraser@colorado.edu
description: A web portfolio for film projects<br /> created, edited, shot, or produced by Taylor Fraser.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "taylorfraser.com" # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: 123.123.1234

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# Build settings
markdown: kramdown

sass:
  style: compressed
