# Site settings
title: Taylor Fraser
subtitle: a Web Portfolio
email: taylor.fraser@colorado.edu
description: A web portfolio for film projects<br /> created, edited, shot, or produced by Taylor Fraser.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "taylorfraser.com" # the base hostname & protocol for your site
author:
city: Nashville
state: TN
phone: 123.123.1234

# url settings
url: "http://taylorfraser.com"
baseurl: ""

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# Build settings
markdown: kramdown

sass:
  style: compressed


# defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts" # previously `page` in Jekyll 2.2.
    values:
      layout: "post" # overrides previous default layout
      author: "Taylor"
